spring:
    datasource:
        url: jdbc:mysql://localhost:3306/board_server?serverTimezone=UTC
        username: root
        password: 1234
        driver-class-name: com.mysql.cj.jdbc.Driver
    
    # redis
    cache:
        type: redis
    data:
        redis:
            host: localhost
            port: 6379
            password: 
            repositories:
                enabled: false

mybatis:
    config-location: classpath:mybatis-config.xml
    mapper-locations: classpath:mappers/*.xml
    configuration:
        map-underscore-to-camel-case: true

expire:
  defaultTime: 36288000
